version: '3.8'

services:
  dev-back:
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    container_name: back-dev
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - /mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis: 
    image: redis
    restart: always
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - redis_data:/data
    
volumes:
  mongo_data:
  redis_data:
