version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./prod.nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on: 
      - dev-front
  prod-front:
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile 
    environment:
      - REACT_APP_BACKEND_URL=/api
      - NODE_ENV=production
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3000
    container_name: prod-front
  prod-back:
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile 
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: prod-back
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis: 
    image: redis
    restart: always
    ports: 
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - redis_data:/data
    
volumes:
  mongo_data:
  redis_data: