services:
  dev-front:
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: front-dev